addons:
  apt:
    packages:
      - python-pygments

install:
  - rm -rf public || exit 0

script:
  - binaries/hugo --theme=minimo --baseUrl=http://shardik.software

after_script:
  - git clone --depth=50 --branch=gh-pages https://github.com/JTaurus19/shardik.website.git
  - git checkout origin/master CNAME
  - git add --all
  - git commit -m "add CNAME from master"
  - git push

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
