addons:
  apt:
    packages:
      - python-pygments

install:
  - rm -rf public || exit 0

script:
  - binaries/hugo --theme=minimo --baseUrl=http://shardik.software
  - cd public
  - echo 'shardik.software' >CNAME
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email:  false
  slack:
     rooms:
       - secure:  "TczDx+uRnrZpGSHrUk69EFgMU7u4lMJ90OVRkaAtccAmftKtE0HYSy0l/joPZUPzFQ2luO2txQzMUOCl+nDhniBfOmCKOjujLuFUVQlVhO9ML+p+LT29IXAssnX1qwYIr7zB9s18k0ySyN4XVecZDQaIli/tuAezn3kvPTvJEmUHCGBhL8jarpy6MBDxJJOFOWU+WC44ZJaBpv16PxoSJyttFkxWGPfuVpqzwIQtVbetT9AG+II3ZOSm+yI7Zs1etuc8hNRhKsXpXlC4kJbxiAWonh544HyxM88c7mB0dx8kef4TTTRfCQo1IMOoaBTQJfkJHzDmwP5rEPWsv30r18psIzba9mZToQlFLQA28WT1uKjCJ53vFvZBl2kJSiqm/7KdwTroukMVg5jtIgCMkQ0wAt7KsOm0SIwYJYL+Hsh13vvplkStOAiYjNpBu7SP97S1qbcJ2bLXKtcvaAqihYnzeDGo0tp3h7y/z+7F5pBFZkimAZyEfOLrTJAcCI5zGJA7vSW+ipFUb4bzZLWpuNLxr1ad01NaBdvJBysSPBYqGiSjb2VgZ9r/MjIzVm1Ygyp3Q2AZ/E0VLyrkp4va7NqRBaWVs7t5PayWKAjvwrhfCzQJX+wNpCN1KmilKeQi3eJkJewUND1ntbvcwvpkTDRQ5chqlcnUK7BN79f23dk="
