addons:
  apt:
    packages:
      - python-pygments

install:
  - rm -rf public || exit 0

script:
  - binaries/hugo --theme=minimo --baseUrl=http://shardik.software
  - cd public
  - echo 'shardik.software' >CNAME
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  slack:  "f7uwXCkWRWQU+Zrz85diFfjFrip3jcY2W7SuH+0ORV5q9pvXlm5JpKNhIMG7CfyRbHi4P7RdGuLPCZeUlkRtiob57s2oH5MuOi5fAzhk7OFsb4w1BbO1NdwkHcvEzJ1ujYapu5+plD+tjo4lIJQhy4bfnxALn7De/F5LJQJbw8UhZiLXxZ2rDEw0nAuLI4SjqyJTCr1+IW6b1PrqkkSChasSS7eYLq9WGKPeEF6GclGlEvcgsjPCHEbTCPGwNGAU6mZU/NnBCQvNuLXPeZdISWbq+PGszobuLGZK2WMbXdO1YTqaAhbhPFzz1I69hxwa4SPU23ga8cRk17DspKiGYMd1ihAAxmjr8mwkIHuDwzBXgE9e83djzgGimn1ei1H3A6FMIOYSxS1jVRqPMFLw+WZBD1REkCtXThMjo2nAOn9HuWPLI7ZS/OmooMRvALXIxmxL8EJTDg59ocA6b0UX2mQV8nMVlYNTn+zQWaj6Yj2Vv6VorFsXfjmBIZ43EbZOoHAISjynFVVH2tY7LconC+H6Sr6+q3ePUVWZWNFHBvqaqYqWkyPqo2Ua7ADZSrcS3EpxnqO/PeGV1d3wLS7ClYlG2MatzI3L6oi4gcFWkp+dzCn07+fS8WGSVcIn5t4MJvgL7wG5biboHacUvha8/58f7MIy9Q86oMOWK98D8do="
