baseURL = "http://shardik.software/"
languageCode = "en-us"
title = "SHARDIK.soft"
theme = 'minimo'
DefaultContentLanguage = "en"

[params]
  customCSS = [ "css/custom.css" ]

[Languages]
[Languages.en]
[Languages.ru]
