baseURL = "http://shardik.com/"
languageCode = "en-us"
title = "SHARDIK"
theme = 'minimo'
DefaultContentLanguage = "en"

enableRobotsTXT = true # generate robots.txt

[params.assets]
  customCSS = [ "css/custom.css", "fontawesome/css/font-awesome.min.css" ]

[params.copyright]
  prefix = ""
  holder = "SHARDIK"
  startYear = "2017"
  suffix = ""
  email = "hello@shardik.software"

[Languages]
[Languages.en]
[Languages.ru]
